### ISSUE TITLE
Edited save has significantly smaller filesize (possibly losing data)

### ISSUE THREAD

**Issue by naturalnumber** [FINDarkside/TLD-Save-Editor#3]
I feel a bit silly opening an issue for this but my curiosity is killing me. I've used the editor a couple of times to fix glitches and such (thanks for making this by the way) but I noticed that the edited save files are usually a lot smaller than the originals, and I'm just wondering why? I took a quick look at the code, but I'll admit C# isn't my best language.

Thanks again!

**Comment by FINDarkside** [comment]
Hi, most of it is because the [compression library](https://github.com/FINDarkside/TLD-Save-Editor/blob/master/The%20Long%20Dark%20Save%20Editor%202/Helpers/CLZF.cs) I use achieves better compression ratio than the one TLD uses. However, it might also be possible that the editor is losing some data from the original save, since it's been a while I've done manual comparing of the saves. I'll keep this issue open until I have made sure the difference is solely because of better compression.

**Comment by naturalnumber** [comment]
If it helps, so far I have not noticed any issues, but thanks.

**Comment by FINDarkside** [comment]
I'm rewriting how the editor loads saves. Once it's done it shouldn't be possible to lose any data. I don't think it's losing lot of data right now, main motivation is to avoid having to update all the data proxies every time the game updates.

**Comment by FINDarkside** [comment]
New save system shouldn't be losing any data. The size difference should be mostly because of better compression and storing binary data as base64 instead of byte arrays converted to text.
